### ISSUE TITLE
this entire assignment

### ISSUE THREAD

**Issue by wasita** [ContextLab/psyc32-eliza#1]
hi @jeremymanning !

just writing this to let you know that i _definitely_ did not give myself as much time as i should have... however, i am much too stubborn to give up even after the submission deadline. i was wondering if there's a way for me to still receive feedback on the assignment even after you've run the autograder on this and have graded the assignment?

thank you!!

**Comment by jeremymanning** [comment]
sure, happy to run it again if you give me a heads up
